# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-01 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lukMsg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lukinfo',
            name='lukSn',
            field=models.CharField(blank=True, default='-', max_length=255, verbose_name='\u77ff\u673a\u5e8f\u53f7'),
        ),
    ]
