# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-28 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lukMsg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LukUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('user_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='lukinfo',
            name='ipAddr',
            field=models.CharField(default='', max_length=255, verbose_name='IP\u5730\u5740'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lukinfo',
            name='macAddr',
            field=models.CharField(default='', max_length=255, verbose_name='MAC\u5730\u5740'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lukinfo',
            name='mechineSensor',
            field=models.CharField(default='', max_length=255, verbose_name='\u673a\u5668\u6e29\u5ea6'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lukinfo',
            name='mechineStat',
            field=models.CharField(default='', max_length=255, verbose_name='\u673a\u5668\u72b6\u6001'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lukinfo',
            name='serverStat',
            field=models.CharField(default='', max_length=255, verbose_name='\u670d\u52a1\u72b6\u6001'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lukinfo',
            name='username',
            field=models.CharField(default='', max_length=255, verbose_name='\u7528\u6237\u540d\u79f0'),
            preserve_default=False,
        ),
    ]
