# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-30 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lukMsg', '0003_lukinfo_runtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lukuser',
            name='id',
        ),
        migrations.AlterField(
            model_name='lukinfo',
            name='ipAddr',
            field=models.CharField(blank=True, max_length=255, verbose_name='IP\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='lukinfo',
            name='mechineSensor',
            field=models.CharField(blank=True, max_length=255, verbose_name='\u673a\u5668\u6e29\u5ea6'),
        ),
        migrations.AlterField(
            model_name='lukinfo',
            name='mechineStat',
            field=models.CharField(blank=True, max_length=255, verbose_name='\u673a\u5668\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='lukinfo',
            name='runTime',
            field=models.CharField(blank=True, max_length=255, verbose_name='\u8fd0\u884c\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='lukinfo',
            name='serverStat',
            field=models.CharField(blank=True, max_length=255, verbose_name='\u670d\u52a1\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='lukinfo',
            name='username',
            field=models.CharField(blank=True, max_length=255, verbose_name='\u7528\u6237\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='lukuser',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
