# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-30 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lukMsg', '0004_auto_20181030_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lukinfo',
            name='macAddr',
            field=models.CharField(max_length=255, unique=True, verbose_name='MAC\u5730\u5740'),
        ),
    ]
